USE BibliothequeConnaissances;
DROP TABLE PRESTAMO;
DROP TABLE LIBRO;
DROP TABLE CATEGORIA;
DROP TABLE PERSONA_AFILIADO;
DROP TABLE PERSONA_BIBLIOTECARIO;
DROP TABLE PERSONA_AUTOR;
DROP TABLE USUARIO;
DROP TABLE TIPO_DOCUMENTO;