INSERT INTO TIPO_DOCUMENTO (NOMBRE,DESCRIPCION)
    VALUES("CC","CEDULA DE CIUDADANIA"),
    ("CE","CEDULA DE EXTRANJERIA"),
    ("TI","TARJETA DE IDENTIDAD");

INSERT INTO USUARIO(USUARIO,CONTRASENA,CORREO,FECHA_MODIFICACION_CLAVE,ROL)
    VALUES("LUCHO","12345678","LUCHO@GMAIL.COM","2021/05/10","ADMINISTRADOR");