INSERT INTO TIPO_DOCUMENTO (NOMBRE,DESCRIPCION)
    VALUES("CC","CEDULA DE CIUDADANIA"),
    ("CE","CEDULA DE EXTRANJERIA"),
    ("TI","TARJETA DE IDENTIDAD");

INSERT INTO USUARIO(USUARIO,CONTRASENA,CORREO,FECHA_MODIFICACION_CLAVE,ROL)
    VALUES("LUCHO","y/p3ZxTVAiAY47DWRjnlkA==","LUCHO@GMAIL.COM","2021/05/10","ADMINISTRADOR"),
            ("MARCELA","y/p3ZxTVAiAY47DWRjnlkA==","MARCELA@GMAIL.COM","2021/05/10","ADMINISTRADOR");